# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QudmatG71U9nvFtMRnnogxEoqvnzoAKP
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameter Definitions
r, K, x_star = 0.12, 2000.0, 1750.0
d, y_star, eps = 0.08, 85.0, 0.0005
a, b, c = 0.0001, 0.00005, 0.0001
c1, c2 = 1.0, 10.0
T, N = 30.0, 3000
dt = T / N
t = np.linspace(0, T, N + 1)

# System ODEs
def system_odes(state, costate):
    x, y = state
    p1, p2 = costate

    # Control updates (bounded)
    u1 = 0.0
    u2 = np.clip(-p2 / (2 * c2), 0.0, 0.5)

    # State dynamics
    dxdt = r * x * (1 - x / K) - a * x * y + u1 * x
    dydt = -d * y + b * x * y - eps * (y**2) - u2 * y

    # Costate dynamics
    dp1dt = -2 * (x - x_star) - p1 * (r * (1 - 2 * x / K) - a * y + u1) - p2 * (b * y)
    dp2dt = -2 * (y - y_star) - p1 * (-a * x) - p2 * (-d + b * x - 2 * eps * y - u2)

    return np.array([dxdt, dydt]), np.array([dp1dt, dp2dt]), u1, u2

# Fourth-Order Runge-Kutta Integrator
def rk4_step(state, costate, dt):
    k1_s, k1_c, u1, u2 = system_odes(state, costate)
    k2_s, k2_c, _, _  = system_odes(state + 0.5 * dt * k1_s, costate + 0.5 * dt * k1_c)
    k3_s, k3_c, _, _  = system_odes(state + 0.5 * dt * k2_s, costate + 0.5 * dt * k2_c)
    k4_s, k4_c, _, _  = system_odes(state + dt * k3_s, costate + dt * k3_c)

    next_state = state + (dt / 6.0) * (k1_s + 2*k2_s + 2*k3_s + k4_s)
    next_costate = costate + (dt / 6.0) * (k1_c + 2*k2_c + 2*k3_c + k4_c)
    return next_state, next_costate, u1, u2

# Forward Simulation Initial Conditions
x0, y0 = 930.0, 100.0
psi1_0, psi2_0 = -12.450, -24.800  # Converged costates

state = np.array([x0, y0])
costate = np.array([psi1_0, psi2_0])

x_hist, y_hist = [x0], [y0]
u1_hist, u2_hist = [], []

for _ in range(N):
    state, costate, u1, u2 = rk4_step(state, costate, dt)
    x_hist.append(state[0])
    y_hist.append(state[1])
    u1_hist.append(u1)
    u2_hist.append(u2)
u2_hist.append(u2_hist[-1])

# Plotting Figure 1: Population Trajectories
plt.figure(figsize=(8, 5))
plt.plot(t, x_hist, 'k-', label=r'Gazelle Density $x(t)$')
plt.plot(t, y_hist, 'k-.', label=r'Wolf Density $y(t)$')
plt.axhline(x_star, color='gray', linestyle=':', label=r'Target $x^*=1750$')
plt.axhline(y_star, color='silver', linestyle=':', label=r'Target $y^*=85$')
plt.xlabel('Time (Years)')
plt.ylabel('Population Density (Individuals)')
plt.title('Figure 1: 30-Year Population Trajectories')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('Fig_1.png', dpi=300)
plt.close()

# Plotting Figure 2: Control Strategy
plt.figure(figsize=(8, 5))
plt.plot(t, u2_hist, 'k-', label=r'Wolf Removal Quota $u_2(t)$')
plt.xlabel('Time (Years)')
plt.ylabel('Control Effort $u_2(t)$')
plt.title('Figure 2: Predator Removal Strategy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('Fig_2.png', dpi=300)
plt.close()